server:
  port: 8070
spring:
  output:
    ansi:
      enabled: always
      #콘솔출력 컬러풀하게
  datasource:
    url: jdbc:h2:~/db_dev;MODE=MySQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true

